spring:
  cloud:
    gcp:
      firestore:
        credentials:
          location: $application.json
      security:
        firebase:
          project-id: metrdotel

gcs:
  resources:
    bucket: metrdotel.appspot.com
